#!/bin/bash

TMP_DIR='/tmp/growthpush-android/'

TOOL_DIR=`dirname $0`
ROOT_DIR="${TOOL_DIR}/../"
FILES=('growthpush.jar' 'android-support-v4.jar' 'google-play-services.jar' 'README.md' 'LICENSE' 'THIRD_PARTY_LICENSES' 'CHANGES')

for FILE in ${FILES[@]}; do
	echo -n "Check ${FILE}... "
	if [ -f ${ROOT_DIR}/${FILE} ]; then
		echo 'exists.'
	else
		echo 'does NOT exist.'
		echo '[FATAL] Failed to verify package.'
		exit 1;
	fi
done

echo 'Unzip growthpush.jar...'
mkdir -p ${TMP_DIR}
rm -r ${TMP_DIR}/* ${TMP_DIR}/.*
unzip ${ROOT_DIR}/growthpush.jar -d ${TMP_DIR}

SOURCES=(`find ${ROOT_DIR}/source/src -name '*.java' -exec basename {} '.java' \;`)
for SOURCE in ${SOURCES[@]}; do
	echo -n "Check ${SOURCE}.java..." 
	if [ `find ${TMP_DIR} -name "${SOURCE}.java" | wc -l` -gt 0 ]; then
		echo 'exists.'
		echo -n "Check ${SOURCE}.class..." 
		if [ `find ${TMP_DIR} -name "${SOURCE}.class" | wc -l` -gt 0 ]; then
			echo 'exists.'
			continue
		fi
	fi
	echo 'does NOT exist.'
	echo '[FATAL] Failed to verify package.'
	exit 1
done

echo '[SUCCESS] Completed to verify package.'
